WebBanHang/Areas/Admin/Controllers/BrandAdminController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHang.Context;

namespace WebBanHang.Areas.Admin.Controllers
{
    public class BrandAdminController : Controller
    {
        // GET: Admin/Brand
        WebBanHangEntities ojbWebBanHangEntities = new WebBanHangEntities();

        // GET: Admin/Brand
        public ActionResult Index(string currentFilter, string SearchString, int? page)
        {
            var lstBrand = ojbWebBanHangEntities.Brand_2119110325.ToList();

            //Số lượng item của trang =6
            int pageSize = 6;
            //sắp xếp theo id sản phẩm, sp mới đưa lên đầu
            int pageNumber = (page ?? 1);
            lstBrand = lstBrand.OrderByDescending(n => n.Id).ToList();
            return View(lstBrand.ToPagedList(pageNumber, pageSize));
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        public ActionResult Error()
        {
            return View();
        }
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Create(Brand_2119110325 brand)
        {
            try
            {
                if (brand.ImageUpload != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(brand.ImageUpload.FileName);
                    string extention = Path.GetExtension(brand.ImageUpload.FileName);
                    fileName = fileName + "_" + long.Parse(DateTime.Now.ToString("yyyyMMddhhmmss")) + extention;
                    brand.Avatar = fileName;
                    brand.ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/Content/images/items"), fileName));
                }
                ojbWebBanHangEntities.Brand_2119110325.Add(brand);
                ojbWebBanHangEntities.SaveChanges();
                return RedirectToAction("Index");

            }
            catch (Exception)
            {

                return RedirectToAction("Lỗi");
            }

        }

        [HttpGet]
        public ActionResult Details(int Id)
        {
            var objProduct = ojbWebBanHangEntities.Brand_2119110325.Where(n => n.Id == Id).FirstOrDefault();
            return View(objProduct);
        }
        [HttpGet]
        public ActionResult Delete(int Id)
        {
            var objProduct = ojbWebBanHangEntities.Brand_2119110325.Where(n => n.Id == Id).FirstOrDefault();
            return View(objProduct);
        }
        [HttpPost]
        public ActionResult Delete(Brand_2119110325 objBrand, int Id)
        {
            objBrand.Id = Id;
            var objcategory = ojbWebBanHangEntities.Brand_2119110325.Where(n => n.Id == objBrand.Id).FirstOrDefault();
            ojbWebBanHangEntities.Brand_2119110325.Remove(objcategory);
            ojbWebBanHangEntities.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int Id)
        {
            var objProduct = ojbWebBanHangEntities.Brand_2119110325.Where(n => n.Id == Id).FirstOrDefault();
            //Session["anhgoc"] = objProduct.Avatar.ToString();
            return View(objProduct);
        }
        [HttpPost]
        public ActionResult Edit(Brand_2119110325 brand)
        {
            try
            {
                if (brand.ImageUpload != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(brand.ImageUpload.FileName);
                    string extension = Path.GetExtension(brand.ImageUpload.FileName);
                    fileName = fileName + extension;
                    brand.Avatar = fileName;
                    brand.ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/Content/images/items"), fileName));
                }
                //else
                //{
                //    brand.Avatar = Session["anhgoc"].ToString();
                //}
                brand.UpdateUtc = DateTime.Now;
                ojbWebBanHangEntities.Entry(brand).State = EntityState.Modified;
                ojbWebBanHangEntities.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Nhập thiếu thông tin");
            }

        }
    }
}

WebBanHang/Areas/Admin/Views/BrandAdmin/Create.cshtml
@model WebBanHang.Context.Brand_2119110325

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<section class="section-content padding-y">
    <div class="card mx-auto" style="max-width:3500px; margin-left:50px;">
        <article class="card-body">
            <div class="content-wrapper">
                <header class="mb-4"><h4 class="text-danger"></h4></header>
                <div class="form-horizontal" style="width :100%">

                    @using (Html.BeginForm("Create", "BrandAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <h4>Thêm thương hiệu</h4>
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Avatar, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    <input type="file" name="ImageUpload" />
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Slug, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Slug, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Slug, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ShowOnHomePage, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.ShowOnHomePage, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ShowOnHomePage, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.DisplayOrder, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.DisplayOrder, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.DisplayOrder, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.CreatedOnUtc, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.CreatedOnUtc, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.CreatedOnUtc, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.UpdateUtc, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.UpdateUtc, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.UpdateUtc, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Deleted, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Deleted, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Deleted, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Thêm" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    }

                    <div>
                        <button> @Html.ActionLink("Quay lại", "Index")</button>

                    </div>
                </div>
            </div>
        </article>
    </div>
</section>

WebBanHang/Areas/Admin/Views/BrandAdmin/Delete.cshtml
@model WebBanHang.Context.Brand_2119110325

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<section class="section-content padding-y">
    <div class="card mx-auto" style="max-width:3500px; margin-left:50px;">
        <article class="card-body">
            <div class="content-wrapper">
                <header class="mb-4"><h4 class="text-danger"></h4></header>
                <div class="form-horizontal" style="width :100%">
                    <h3>Bạn có muốn xoá Thương hiệu này không ?</h3>
                    <div>
                        <h4>Thông tin thương hiệu</h4>
                        <hr />
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.Name)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Name)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Avatar)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Avatar)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Slug)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Slug)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.ShowOnHomePage)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.ShowOnHomePage)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.DisplayOrder)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.DisplayOrder)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.CreatedOnUtc)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.CreatedOnUtc)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.UpdateUtc)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.UpdateUtc)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Deleted)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Deleted)
                            </dd>

                        </dl>

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <input type="submit" value="Xoá" class="btn btn-default" />
                                <button>@Html.ActionLink("Quay lại", "Index")</button>

                            </div>
                        }
                    </div>
                </div>
            </div>
        </article>
    </div>
</section>

WebBanHang/Areas/Admin/Views/BrandAdmin/Details.cshtml
@model WebBanHang.Context.Brand_2119110325

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<section class="section-content padding-y">
    <div class="card mx-auto" style="max-width:3500px; margin-left:50px;">
        <article class="card-body">
            <div class="content-wrapper">
                <header class="mb-4"><h4 class="text-danger"></h4></header>
                <div class="form-horizontal" style="width :100%">

                    <div>
                        <h4>Chi tiết thương hiệu</h4>
                        <hr />
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.Name)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Name)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Avatar)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Avatar)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Slug)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Slug)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.ShowOnHomePage)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.ShowOnHomePage)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.DisplayOrder)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.DisplayOrder)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.CreatedOnUtc)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.CreatedOnUtc)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.UpdateUtc)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.UpdateUtc)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Deleted)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Deleted)
                            </dd>

                        </dl>
                    </div>
                    <p>
                        <button>@Html.ActionLink("Sửa", "Edit", new { id = Model.Id })</button>
                        <button> @Html.ActionLink("Quay lại", "Index")</button>


                    </p>
                </div>
            </div>
        </article>
    </div>
</section>

WebBanHang/Areas/Admin/Views/BrandAdmin/Edit.cshtml
@model WebBanHang.Context.Brand_2119110325

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<section class="section-content padding-y">
    <div class="card mx-auto" style="max-width:3500px; margin-left:50px;">
        <article class="card-body">
            <div class="content-wrapper">
                <header class="mb-4"><h4 class="text-danger"></h4></header>
                <div class="form-horizontal" style="width :100%">
                    @using (Html.BeginForm("Edit", "BrandAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <h4>Sửa thương hiệu</h4>
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.Id)

                            <div class="form-group">
                                @Html.LabelFor(model => model.Name, "Tên", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Avatar, "Hình ảnh", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    <input type="file" name="ImageUpload" />
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Slug, "Thương hiệu", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Slug, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Slug, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ShowOnHomePage, "Hiện trang chủ", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.ShowOnHomePage, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ShowOnHomePage, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            @*<div class="form-group">
                                @Html.LabelFor(model => model.DisplayOrder, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.DisplayOrder, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.DisplayOrder, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.CreatedOnUtc, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.CreatedOnUtc, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.CreatedOnUtc, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.UpdateUtc, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.UpdateUtc, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.UpdateUtc, "", new { @class = "text-danger" })
                                </div>
                            </div>*@

                            @*<div class="form-group">
                                @Html.LabelFor(model => model.Deleted, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Deleted, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Deleted, "", new { @class = "text-danger" })
                                </div>
                            </div>*@

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Lưu" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    }

                    <div>
                        <button> @Html.ActionLink("Quay lại", "Index")</button>

                    </div>
                </div>
            </div>
        </article>
    </div>
</section>

WebBanHang/Areas/Admin/Views/BrandAdmin/Index.cshtml
@model PagedList.IPagedList<WebBanHang.Context.Brand_2119110325>
@using PagedList;

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<section class="section-content padding-y">
    <div class="card mx-auto" style="max-width:3500px; margin-left:50px;">
        <article class="card-body">
            <div class="content-wrapper"> 
                <header class="mb-4"><h4 class="text-danger"></h4></header>
                <div class="form-horizontal" style="width :100%">

                    <p>
                        @Html.ActionLink("Thêm mới", "Create")
                    </p>
                    <table class="table">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.FirstOrDefault().Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.FirstOrDefault().Avatar)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.FirstOrDefault().Slug)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.FirstOrDefault().ShowOnHomePage)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.FirstOrDefault().DisplayOrder)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.FirstOrDefault().CreatedOnUtc)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.FirstOrDefault().UpdateUtc)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.FirstOrDefault().Deleted)
                            </th>
                            <th></th>
                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    <img id="Avatar" class="hide" src="~/Content/images/items/@item.Avatar" width="107" height="98" alt="" />
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Slug)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ShowOnHomePage)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.DisplayOrder)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CreatedOnUtc)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.UpdateUtc)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Deleted)
                                </td>
                                <td>
                                    <button style="width:100px">@Html.ActionLink("Sửa", "Edit", new { id = item.Id })</button>  <br />
                                    <button style="width:100px"> @Html.ActionLink("Chi tiết", "Details", new { id = item.Id })</button> <br />
                                    <button style="width:100px">@Html.ActionLink("Xoá", "Delete", new { id = item.Id })</button>

                                </td>
                            </tr>
                        }

                    </table>
                </div>
            </div>
        </article>
    </div>
</section>