WebBanHang/Areas/Admin/Controllers/CategoryAdminController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHang.Context;

namespace WebBanHang.Areas.Admin.Controllers
{
    public class CategoryAdminController : Controller
    {
        // GET: Admin/CategoryAdmin
        WebBanHangEntities ojbWebBanHangEntities = new WebBanHangEntities();

        public ActionResult Index(string currentFilter, string SearchString, int? page)
        {
            var lstCategory = new List<Category_2119110325>();
            if (SearchString != null)
            {
                page = 1;
            }
            else
            {
                SearchString = currentFilter;
            }
            if (!string.IsNullOrEmpty(SearchString))
            {
                //lấy tất cả các danh mucc theo từ khóa tìm kiếm
                lstCategory = ojbWebBanHangEntities.Category_2119110325.Where(n => n.Name.Contains(SearchString)).ToList();
            }
            else
            { //lấy tất cả các danh mục trong category
                lstCategory = ojbWebBanHangEntities.Category_2119110325.ToList();
            }
            ViewBag.CurrentFilter = SearchString;
            //Số lượng item của trang =6
            int pageSize = 6;
            //sắp xếp theo id sản phẩm, sp mới đưa lên đầu
            int pageNumber = (page ?? 1);
            lstCategory = lstCategory.OrderByDescending(n => n.Id).ToList();
            return View(lstCategory.ToPagedList(pageNumber, pageSize));
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Create(Category_2119110325 category)
        {
            try
            {
                if (category.ImageUpload != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(category.ImageUpload.FileName);
                    string extention = Path.GetExtension(category.ImageUpload.FileName);
                    fileName = fileName + "_" + long.Parse(DateTime.Now.ToString("yyyyMMddhhmmss")) + extention;
                    category.Avatar = fileName;
                    category.ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/Content/images/items"), fileName));
                }
                ojbWebBanHangEntities.Category_2119110325.Add(category);
                ojbWebBanHangEntities.SaveChanges();
                return RedirectToAction("Index");

            }
            catch (Exception)
            {

                return RedirectToAction("Lỗi");
            }
        }

        [HttpGet]
        public ActionResult Details(int Id)
        {
            var objProduct = ojbWebBanHangEntities.Category_2119110325.Where(n => n.Id == Id).FirstOrDefault();
            return View(objProduct);
        }
        [HttpGet]
        public ActionResult Delete(int Id)
        {
            var objProduct = ojbWebBanHangEntities.Category_2119110325.Where(n => n.Id == Id).FirstOrDefault();
            return View(objProduct);
        }
        [HttpPost]
        public ActionResult Delete(Category_2119110325 objCate, int Id)
        {
            objCate.Id = Id;
            var objcategory = ojbWebBanHangEntities.Category_2119110325.Where(n => n.Id == objCate.Id).FirstOrDefault();
            ojbWebBanHangEntities.Category_2119110325.Remove(objcategory);
            ojbWebBanHangEntities.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int Id)
        {
            var objProduct = ojbWebBanHangEntities.Category_2119110325.Where(n => n.Id == Id).FirstOrDefault();
            return View(objProduct);
        }
        [HttpPost]
        public ActionResult Edit(Category_2119110325 category)
        {
            try
            {
                if (category.ImageUpload != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(category.ImageUpload.FileName);
                    string extension = Path.GetExtension(category.ImageUpload.FileName);
                    fileName = fileName + extension;
                    category.Avatar = fileName;
                    category.ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/Content/images/items"), fileName));
                }
                category.UpdatedOnUtc = DateTime.Now;
                ojbWebBanHangEntities.Entry(category).State = EntityState.Modified;
                ojbWebBanHangEntities.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Error");
            }
        }
    }
}

WebBanHang/Areas/Admin/Views/CategoryAdmin/Create.cshtml
@model WebBanHang.Context.Category_2119110325

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<section class="section-content padding-y">
    <div class="card mx-auto" style="max-width:3500px; margin-left:50px;">
        <article class="card-body">
            <div class="content-wrapper">
                <div class="form-horizontal" style="width :100%">
                    <h4>Nhập thông tin</h4>

                    @using (Html.BeginForm("Create", "CategoryAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Avatar, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    <input type="file" name="ImageUpload" />
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Slug, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Slug, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Slug, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ShowOnHomePage, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.ShowOnHomePage, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ShowOnHomePage, "", new { @class = "text-danger" })
                                </div>
                            </div>


                            <div class="form-group">
                                @Html.LabelFor(model => model.Deleted, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Deleted, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Deleted, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Thêm" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    }

                    <div>
                        @Html.ActionLink("Quay lại", "Index")
                    </div>
                </div>
            </div>
        </article>
    </div>
</section>

WebBanHang/Areas/Admin/Views/CategoryAdmin/Delete.cshtml
@model WebBanHang.Context.Category_2119110325

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<section class="section-content padding-y">
    <div class="card mx-auto" style="max-width:3500px; margin-left:50px;">
        <article class="card-body">
            <div class="content-wrapper">
                <header class="mb-4"><h4 class="text-danger"></h4></header>
                <div class="form-horizontal" style="width :100%">


                    <h3>Bạn có muốn xoá sản phầm này ?</h3>
                    <div>
                        <h4>Thông tin sản phẩm</h4>
                        <hr />
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.Name)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Name)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Avatar)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Avatar)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Slug)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Slug)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.ShowOnHomePage)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.ShowOnHomePage)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.DisplayOrder)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.DisplayOrder)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Deleted)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Deleted)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.CreatedOnUtc)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.CreatedOnUtc)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.UpdatedOnUtc)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.UpdatedOnUtc)
                            </dd>

                        </dl>

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <input type="submit" value="Xoá" class="btn btn-default" />
                                <button> @Html.ActionLink("Quay Lại", "Index")</button>

                            </div>
                        }
                    </div>
                </div>
            </div>
        </article>
    </div>
</section>

WebBanHang/Areas/Admin/Views/CategoryAdmin/Details.cshtml
@model WebBanHang.Context.Category_2119110325

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<section class="section-content padding-y">
    <div class="card mx-auto" style="max-width:3500px; margin-left:50px;">
        <article class="card-body">
            <div class="content-wrapper">
                <header class="mb-4"><h4 class="text-danger"></h4></header>
                <div class="form-horizontal" style="width :100%">
                    <h4>Trang chi tiết sản phẩm</h4>
                    <div>
                        <h4>Thông tin sản phẩm</h4>
                        <hr />
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.Name)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Name)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Avatar)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Avatar)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Slug)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Slug)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.ShowOnHomePage)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.ShowOnHomePage)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.DisplayOrder)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.DisplayOrder)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Deleted)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Deleted)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.CreatedOnUtc)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.CreatedOnUtc)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.UpdatedOnUtc)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.UpdatedOnUtc)
                            </dd>

                        </dl>
                    </div>
                    <p>
                        <button>@Html.ActionLink("Sửa", "Edit", new { id = Model.Id })</button>
                        <button>@Html.ActionLink("Quay lại", "Index")</button>


                    </p>
                </div>
            </div>
        </article>
    </div>
</section>

WebBanHang/Areas/Admin/Views/CategoryAdmin/Edit.cshtml
@model WebBanHang.Context.Category_2119110325

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<section class="section-content padding-y">
    <div class="card mx-auto" style="max-width:3500px; margin-left:50px;">
        <article class="card-body">
            <div class="content-wrapper">
                <header class="mb-4"><h4 class="text-danger"></h4></header>
                <div class="form-horizontal" style="width :100%">

                    <div>

                        @using (Html.BeginForm("Edit", "CategoryAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                <h4>Sửa danh mục</h4>
                                <hr />
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.Id)

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Name, "Tên", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Avatar, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">

                                        <input type="file" name="ImageUpload" />
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Slug, "Tên gọi", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Slug, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Slug, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                @*<div class="form-group">
                                        @Html.LabelFor(model => model.ShowOnHomePage, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.ShowOnHomePage, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.ShowOnHomePage, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.DisplayOrder, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.DisplayOrder, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.DisplayOrder, "", new { @class = "text-danger" })
                                        </div>*@
                                @*</div>*@

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Deleted, "Có thể xoá", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Deleted, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Deleted, "", new { @class = "text-danger" })
                                    </div>
                                </div>


                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Lưu" class="btn btn-default" />
                                    </div>
                                </div>
                            </div>
                        }

                        <div>
                            <button> @Html.ActionLink("Quay lại", "Index")</button>

                        </div>

                    </div>
                </div>
        </article>
    </div>
</section>

WebBanHang/Areas/Admin/Views/CategoryAdmin/Index.cshtml
@model IEnumerable<WebBanHang.Context.Category_2119110325>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<section class="section-content padding-y">
    <div class="card mx-auto" style="max-width:3500px; margin-left:50px;">
        <article class="card-body">
            <div class="content-wrapper">
                <header class="mb-4"><h4 class="text-danger"></h4></header>
                <div class="form-horizontal" style="width :100%">
                    <h4>Trang danh mục</h4>

                    <p>
                        @Html.ActionLink("Thêm mới", "Create")
                    </p>
                    <table class="table">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.FirstOrDefault().Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.FirstOrDefault().Avatar)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.FirstOrDefault().Slug)
                            </th>
                            @*<th>
                                    @Html.DisplayNameFor(model => model.ShowOnHomePage)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.DisplayOrder)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Deleted)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CreatedOnUtc)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.UpdatedOnUtc)
                                </th>*@
                            <th></th>
                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    <img id="Avatar" class="hide" src="~/Content/images/items/@item.Avatar" width="107" height="98" alt="" />
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Slug)
                                </td>
                                @*<td>
                                        @Html.DisplayFor(modelItem => item.ShowOnHomePage)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DisplayOrder)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Deleted)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CreatedOnUtc)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.UpdatedOnUtc)
                                    </td>*@
                                <td>
                                    <button>@Html.ActionLink("Sửa", "Edit", new { id = item.Id })</button>
                                    <button> @Html.ActionLink("Chi tiết", "Details", new { id = item.Id })</button>
                                    <button>@Html.ActionLink("Xoá", "Delete", new { id = item.Id })</button>

                                </td>
                            </tr>
}

                    </table>

                </div>
            </div>
        </article>

    </div>
</section>